server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.40.107.7:3306/test_db?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3c6cc3480c235348

rpc:
  api-config:
    api-key:
      kimi: sk-0TsvAhmvcwF8W0oLc5TTq5kPrHx91zQum9S2nONTiLkSqlg3
      deepseek: sk-c5f811085f2f418fbd6bac939415a43a

    qwen-chat:
      url: "https://api.qwen.com/chat"
      timeout: 5000
    kimi-chat:
      url: "https://api.moonshot.cn/v1/chat/completions"
      timeout: 8000
    deepseek:
      url: "https://api.deepseek.com/chat/completions"
      timeout: 8000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: tech.pdai.springboot.mysql57.xml.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
